In [2]:
import numpy as np
import networkx as nx
from numpy import linalg

In [3]:
H = np.matrix('1 0 0; 1 1 0; 0 1 0; 0 1 1; 0 0 1')

In [4]:
Dv = np.matrix('1 0 0 0 0; \
               0 0.5 0 0 0; \
               0 0 1 0 0; \
               0 0 0 0.5 0;\
               0 0 0 0 1\
               ')

In [5]:
Dv

matrix([[ 1. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.5,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ]])

In [6]:
Ht = H.transpose()

In [7]:
Ht

matrix([[1, 1, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1]])

In [8]:
a = H.T

In [9]:
a

matrix([[1, 1, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1]])

In [10]:
De = np.matrix('0.5 0 0; \
               0 0.333 0; \
               0  0 0.5 \
               ')

In [11]:
De

matrix([[ 0.5  ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.5  ]])

In [12]:
1./3

0.3333333333333333

In [13]:
np.dot(De, Ht)

matrix([[ 0.5  ,  0.5  ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.333,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.5  ,  0.5  ]])

In [14]:
De.dot(Ht)

matrix([[ 0.5  ,  0.5  ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.333,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.5  ,  0.5  ]])

In [15]:
Dv.dot(H)

matrix([[ 1. ,  0. ,  0. ],
        [ 0.5,  0.5,  0. ],
        [ 0. ,  1. ,  0. ],
        [ 0. ,  0.5,  0.5],
        [ 0. ,  0. ,  1. ]])

In [16]:
Dv.dot(H).dot(De.dot(Ht))

matrix([[ 0.5   ,  0.5   ,  0.    ,  0.    ,  0.    ],
        [ 0.25  ,  0.4165,  0.1665,  0.1665,  0.    ],
        [ 0.    ,  0.333 ,  0.333 ,  0.333 ,  0.    ],
        [ 0.    ,  0.1665,  0.1665,  0.4165,  0.25  ],
        [ 0.    ,  0.    ,  0.    ,  0.5   ,  0.5   ]])

In [17]:
.25+.4165+.1665+.1665

0.9994999999999999

In [18]:
M =(Dv.dot(H).dot(De.dot(Ht))).T

In [19]:
M

matrix([[ 0.5   ,  0.25  ,  0.    ,  0.    ,  0.    ],
        [ 0.5   ,  0.4165,  0.333 ,  0.1665,  0.    ],
        [ 0.    ,  0.1665,  0.333 ,  0.1665,  0.    ],
        [ 0.    ,  0.1665,  0.333 ,  0.4165,  0.5   ],
        [ 0.    ,  0.    ,  0.    ,  0.25  ,  0.5   ]])

In [20]:
matSize = len(M)
print matSize

5


In [21]:
teleMat = [[1./matSize  for j in range(matSize)] for i in range(matSize)]

In [22]:
teleMat

[[0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2]]

In [23]:
type(teleMat)

list

In [24]:
teleMat = np.matrix(teleMat)

In [26]:
MH2 = 0.85 * M + 0.15 * teleMat

In [27]:
evalM, evecM = linalg.eig(MH2)
print evalM, "\n"
print evecM

[  9.99641470e-01 +0.00000000e+00j   6.37500000e-01 +0.00000000e+00j
   3.53958530e-01 +0.00000000e+00j  -1.16608786e-17 +2.32327558e-17j
  -1.16608786e-17 -2.32327558e-17j] 

[[  3.27930869e-01 +0.00000000e+00j   5.00000000e-01 +0.00000000e+00j
    4.99801610e-01 +0.00000000e+00j  -3.36792671e-01 +1.11022302e-16j
   -3.36792671e-01 -1.11022302e-16j]
 [  5.84046528e-01 +0.00000000e+00j   5.00000000e-01 +0.00000000e+00j
   -1.66935208e-01 +0.00000000e+00j   6.73585342e-01 +0.00000000e+00j
    6.73585342e-01 -0.00000000e+00j]
 [  3.20471522e-01 +0.00000000e+00j  -5.93205949e-16 +0.00000000e+00j
   -6.66829794e-01 +0.00000000e+00j  -4.48507750e-01 +1.67974694e-01j
   -4.48507750e-01 -1.67974694e-01j]
 [  5.84046528e-01 +0.00000000e+00j  -5.00000000e-01 +0.00000000e+00j
   -1.66935208e-01 +0.00000000e+00j   2.23430158e-01 -3.35949388e-01j
    2.23430158e-01 +3.35949388e-01j]
 [  3.27930869e-01 +0.00000000e+00j  -5.00000000e-01 +0.00000000e+00j
    4.99801610e-01 +0.00000000e+00j  -1.117150

In [ ]:
from numpy import linalg
M = [[1, 0, 0], [0, 0, 1], ...]
evalM, evecM = linalg.eig(M)
print evalM							# eigenvalores
>>>[-0.85, 1.23, 0.85, 0.62, -0.85, 0.0]
print evecM[:, 1]
>>>[3.3, 5.0, 3.8, 1.0, 1.0, 1.0]