In [1]:
import numpy as np
import networkx as nx

In [2]:
H = np.matrix('1 0 0; 1 1 0; 0 1 0; 0 1 1; 0 0 1')

In [4]:
Dv = np.matrix('1 0 0 0 0; \
               0 0.5 0 0 0; \
               0 0 1 0 0; \
               0 0 0 0.5 0;\
               0 0 0 0 1\
               ')

In [13]:
Dv

matrix([[ 1. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.5,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  1. ]])

In [6]:
Ht = H.transpose()

In [14]:
Ht

matrix([[1, 1, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1]])

In [23]:
a = H.T

In [24]:
a

matrix([[1, 1, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1]])

In [19]:
De = np.matrix('0.5 0 0; \
               0 0.333 0; \
               0  0 0.5 \
               ')

In [20]:
De

matrix([[ 0.5  ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.5  ]])

In [16]:
1./3

0.3333333333333333

In [21]:
np.dot(De, Ht)

matrix([[ 0.5  ,  0.5  ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.333,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.5  ,  0.5  ]])

In [22]:
De.dot(Ht)

matrix([[ 0.5  ,  0.5  ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.333,  0.333,  0.333,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.5  ,  0.5  ]])

In [25]:
Dv.dot(H)

matrix([[ 1. ,  0. ,  0. ],
        [ 0.5,  0.5,  0. ],
        [ 0. ,  1. ,  0. ],
        [ 0. ,  0.5,  0.5],
        [ 0. ,  0. ,  1. ]])

In [26]:
Dv.dot(H).dot(De.dot(Ht))

matrix([[ 0.5   ,  0.5   ,  0.    ,  0.    ,  0.    ],
        [ 0.25  ,  0.4165,  0.1665,  0.1665,  0.    ],
        [ 0.    ,  0.333 ,  0.333 ,  0.333 ,  0.    ],
        [ 0.    ,  0.1665,  0.1665,  0.4165,  0.25  ],
        [ 0.    ,  0.    ,  0.    ,  0.5   ,  0.5   ]])

In [27]:
.25+.4165+.1665+.1665file:///home/carlos/maestria/TESIS/CODE/08prfb/comm-jup.ipynb

0.9994999999999999

In [29]:
M =(Dv.dot(H).dot(De.dot(Ht))).T

In [30]:
M

matrix([[ 0.5   ,  0.25  ,  0.    ,  0.    ,  0.    ],
        [ 0.5   ,  0.4165,  0.333 ,  0.1665,  0.    ],
        [ 0.    ,  0.1665,  0.333 ,  0.1665,  0.    ],
        [ 0.    ,  0.1665,  0.333 ,  0.4165,  0.5   ],
        [ 0.    ,  0.    ,  0.    ,  0.25  ,  0.5   ]])

In [35]:
matSize = len(M)
print matSize

5


In [36]:
newMat = [[1./matSize  for j in range(matSize)] for i in range(matSize)]

In [37]:
newMat

[[0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2],
 [0.2, 0.2, 0.2, 0.2, 0.2]]

In [ ]:
from numpy import linalg
M = [[1, 0, 0], [0, 0, 1], ...]
evalM, evecM = linalg.eig(M)
print evalM							# eigenvalores
>>>[-0.85, 1.23, 0.85, 0.62, -0.85, 0.0]
print evecM[:, 1]
>>>[3.3, 5.0, 3.8, 1.0, 1.0, 1.0]