In [1]:
a = [(1, 2), (3, 4)]

In [2]:
a.extend([(10, 11), (23, 34)])

In [3]:
a

[(1, 2), (3, 4), (10, 11), (23, 34)]

In [4]:
import numpy as np


In [5]:
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
v = csr_matrix([[5, 0, 0], [0, 5, 0], [0, 0, 5]])
print A.dot(v)

  (0, 1)	10
  (0, 0)	5
  (1, 2)	15
  (2, 2)	25
  (2, 0)	20


In [6]:
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
v = csr_matrix([[5, 0], [0, 5], [0, 0]])
print A.dot(v)

  (0, 1)	10
  (0, 0)	5
  (2, 0)	20


In [7]:
row = np.array([0, 2, 2])
col = np.array([0, 0, 1])
data = np.array([1, 4, 5])
v = csr_matrix((data, (row, col)), shape=(3, 2)).toarray()
print v

[[1 0]
 [0 0]
 [4 5]]


In [8]:
print A.dot(v)

[[ 1  0]
 [12 15]
 [24 25]]


In [9]:
row = np.array([0, 2, 2])
col = np.array([0, 0, 1])
data = np.array([1, 4, 5])
v = csr_matrix((data, (row, col)), shape=(3, 2))
print v

  (0, 0)	1
  (2, 0)	4
  (2, 1)	5


In [10]:
print A.dot(v)

  (0, 0)	1
  (1, 1)	15
  (1, 0)	12
  (2, 1)	25
  (2, 0)	24


In [11]:
a = [[3], [2], [1]]
print sorted(a)

[[1], [2], [3]]


In [12]:
import snap


In [13]:
G1 = snap.TUNGraph.New()

In [14]:
a = [(1, 2), (3, 4)]

In [15]:
a

[(1, 2), (3, 4)]

In [16]:
G1.AddNode(1)
G1.AddNode(2)
G1.AddNode(3)
G1.AddNode(4)
G1.AddNode(10)

10

In [17]:
G1.AddEdge(a[0][0], a[0][1])

-1

In [18]:
for edge in a:
    G1.AddEdge(edge[0], edge[1])

In [19]:
print G1

<snap.PUNGraph; proxy of <Swig Object of type 'PUNGraph *' at 0x7fa248877210> >


In [ ]:
# tests for snap community detection

In [2]:
import pprint
outFileName = "data/communities.txt"


In [9]:
def leer_texto2(fp):
    tmpFull = []
    initialGroup = 0
    # procesamiento de archivo de entrada completo
    for line in fp:
        tmp = line.split()
        #ok print tmp
        tmp2 = [int(item) for item in tmp]
        for item2 in tmp2:
            tmpFull.append((item2, initialGroup))
        initialGroup += 1

    # regresa una lista con todas las palabras del texto en esa lista
    return tmpFull

In [ ]:
    inFilePointer02 = open(outFileName, "r")
    communitiesL = leer_texto2(inFilePointer02)
    print communitiesL[:10]
    pprint.pprint(communitiesL)

In [ ]:
misc tests

In [15]:
a = {"a":1, "b":2}
list(a.items())

[('a', 1), ('b', 2)]

In [13]:
a = list(a.items())

In [16]:
a

{'a': 1, 'b': 2}

In [17]:
list(a)

['a', 'b']

In [18]:
a

{'a': 1, 'b': 2}

In [19]:
import operator


In [22]:
b = list(a)
b

['a', 'b']

In [24]:
c = [b, b, b]
c

[['a', 'b'], ['a', 'b'], ['a', 'b']]

In [26]:
print c, operator.itemgetter(0)

[['a', 'b'], ['a', 'b'], ['a', 'b']] <operator.itemgetter object at 0x7fc9b03efad0>


In [27]:
f  = operator.itemgetter(0)
[f(c) for item in ]

['a', 'b']

In [8]:
#2016JUN10 MARKOV CHAIN EXAMPLE (from Wikipedia)

import numpy as np
import math


In [9]:
A = np.matrix([[0.9, 0.075, 0.025], [0.15, 0.8, 0.05], [0.25, 0.25, 0.5]]) # row stochastic
v = np.matrix([0, 1, 0])

In [10]:
def it(A, v):
    MAX_ITER = 100 # works ok for simple cases of PageRank
    MAX_ITER = 100000
    EPS = 1.0e-6 # works ok for simple cases of PageRank
    EPS = 1.0e-18
    for i in range(MAX_ITER):
        # guardamos el vector anterior
        vOld = v.copy()
        # calculamos el vector nuevo
        z = np.dot(A, v)
        # print("z", z)
        # z2 = mulMatVecCUDA(A, v)
        # print("z2", z2)
        # calculamos su magnitud
        zMag = math.sqrt(np.dot(z.T, z))
        # print("zMag", zMag)
        # dividimos vector entre la norma para normalizar
        v = z / zMag
        if np.dot(vOld.T, v) < 0.0:
            sign = -1.0
            v = -v
        else:
            sign = 1.0

        # Condición de terminación
        vecDif = vOld - v
        if math.sqrt(np.dot(vecDif.T, vecDif)) < EPS:
            break

    print("num iters = ", i)

    eigVal = sign * zMag
    # Another way to get eigVal
    # eigValAnother = np.dot(v.T, np.dot(A, v))
    # print("eigValAnother = ", eigValAnother)

    # eigVec = v
    return eigVal, v

In [15]:
A2, v2 = it(A, v.T)
print A2, "\n", v2 # this obtains incorrect results

('num iters = ', 122)
1.0 
[[ 0.57735027]
 [ 0.57735027]
 [ 0.57735027]]


In [16]:
A3, v3 = it(v, A)
print A3, "\n", v3

TypeError: only length-1 arrays can be converted to Python scalars